### ISSUE TITLE
[1.16.5][Mod] IndustrialForegoing BlockPlacer Sign Crash

### ISSUE THREAD

**Issue by TheMartinfer22** [Mohist-Community/Mohist#1059]
Hello, this is a continuation of topic #1052 where the crash with other blocks was fixed in relation to the **fakeplayer** but there is another one when you put signs, generating the same error.

Mohist Version: 403

Crash Report: https://ghostbin.com/paste/q9mJH
How to crash: https://i.imgur.com/RLZxgLa.png
Error: https://i.imgur.com/UmLDY7t.png

**Comment by KR33PY** [comment]
Fixed in 8085e8c
