### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by Fabian274** [Mohist-Community/Mohist#3]
[01:45:28] [main/ERROR] [mixin]: Critical injection failure: LVT in net/minecraft/world/World::func_72939_s()V has incompatible changes at opcode 855 in callback net/minecraft/world/World::handler$beforeTick$zzp000.
Expected: [Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;, Lnet/minecraft/util/math/BlockPos;]
   Found: [Ljava/util/Set;, I, I, Lnet/minecraft/tileentity/TileEntity;, Lnet/minecraft/util/math/BlockPos;]

**Comment by Mgazul** [comment]
Do you know which mod caused this

**Comment by Fabian274** [comment]
Yes I just tried it is the mod
https://www.curseforge.com/minecraft/mc-mods/laggoggles

**Comment by Mgazul** [comment]
This mod is currently not compatible, we have studied

**Comment by Fabian274** [comment]
will there be a fix?

**Comment by Mgazul** [comment]
The future may be, but not now

**Comment by Mgazul** [comment]
The future may be fixed, temporarily close this!
