### ISSUE TITLE
考古学家勘察此项目

### ISSUE THREAD

**Issue by 8MiYile** [Mohist-Community/Mohist#349]
发现该项目出现了创站前的数据，已成立github调查小组前来调查此项目

**Comment by CarierxGroup** [comment]
not a issue

**Comment by MCUmbrella** [comment]
调查组发现此事件与Mohist某开发人员（@CraftDream）有一定关联，现已将调查方向转至此人，等待进一步分析结果

**Comment by 8MiYile** [comment]
案情正在进一步跟踪调查，以及消失的20世纪项目数据
